### ISSUE TITLE
Schema Change

### ISSUE THREAD

**Issue by siefkenj** [siefkenj/tafs#249]
`survey_instances` should contain a copy of the name of the survey and names longer than 256 chars should be allowed.

**Comment by F-Ting** [comment]
Is there a fixed size for the names you have in mind? I was thinking varchar(1000). Also would you only want to change the name size for `survey_instances`?

**Comment by siefkenj** [comment]
Probably `512` is good. The `name` should have a consistent size everywhere it comes up. Also, while we're at it, let's make the `term` length 50 everywhere it appears. On second thought, let's have 50 be the minimum size across the board.

**Comment by F-Ting** [comment]
Sounds good
