### ISSUE TITLE
Inconsistent column field name

### ISSUE THREAD

**Issue by richardzeng1** [siefkenj/tafs#26]
courses table has column name course_code. sections table has column name course_id. 

Inconsistent column name not only causes confusion but also causes the GET request to fail.

**Comment by richardzeng1** [comment]
@DarrenZhang01 This issue has not been resolved. Don't close issues that have not been solved.

**Comment by DarrenZhang01** [comment]
#32

**Comment by DarrenZhang01** [comment]
@richardzeng1 I concatenate all the issues about the database schema into one issue.
