### ISSUE TITLE
Survey Questions Not Showing

### ISSUE THREAD

**Issue by richardzeng1** [siefkenj/tafs#81]
On surveys page, survey questions are not showing up.
<img width="1021" alt="screen shot 2018-07-03 at 10 22 54 am" src="https://user-images.githubusercontent.com/26105138/42225679-1a76c5b8-7eab-11e8-9a41-abce9beb2202.png">

**Comment by DarrenZhang01** [comment]
Since the get_info.php is currently being changed, the data format returned back from the API is changing. So this survey component is not  the final version. I will make changes according to the final version of get_info.php and post_info.php to this survey component.
